YAML
name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - name: Deploy to staging
        uses: ./.github/actions/deploy-to-staging
        env:
          STAGING_ENV: true
      - name: Deploy to production
        uses: ./.github/actions/deploy-to-production
        env:
          PRODUCTION_ENV: true
